### ISSUE TITLE
Comments about "Limitations and Alternatives" 

### ISSUE THREAD

**Issue by lemmy** [mwhittaker/tla_talk#1]
A few comments about the "Limitations and Alternatives" section:

> Model checkers exhaustively enumerate executions looking for errors, but they're not proving anything about the correctness of your specification.

For the (finite) model, TLC actually checks the correctness of the specification for the stated safety and liveness properties.  For simple algorithms - such as the one below (taken from [here](https://lamport.azurewebsites.net/tla/proving-safety.pdf)) - TLC can even check the complete algorithm, not just a model of it.

```tla
EXTENDS Integers
(*****
--algorithm SimpleMutex {
  variables flag = [i \in {0, 1} |-> FALSE] ;
    process (proc \in {0,1}) {
         s1: while (TRUE) {
                  flag[self] := TRUE ;
         s2:
                  await flag[1-self] = FALSE ;
         cs:
                  skip ;
         s3:
                  flag[self] := FALSE
    }
  }
}
*****)
```

If one needs higher assurances for infinite models, TLA+ comes with a [proof system](https://tla.msr-inria.inria.fr/tlaps/content/Home.html) to write machine checked proofs.  Usually people combine the powers of TLC and TLAPS (see [Proving Safety Properties](https://lamport.azurewebsites.net/tla/proving-safety.pdf) and [Using TLC to Check Inductive Invariance](https://lamport.azurewebsites.net/tla/inductive-invariant.pdf)).

> If there are infinite executions, you cannot check all of them.

Infinite executions do not imply that the state space is infinite. By definition a behavior is always an infinite sequence of states (a terminating execution has a suffix of infinite stuttering). TLC can easily check specs that allow infinitely many behaviors:

```tla
VARIABLE x
Spec == x = 0 /\ [][x' \in {0,1}]_x
```

TLC checks this specification in less than a second. Do not replace {0,1} with Nat though! ;-)

> Need to resort to automated theorem proving for really being confident that code is bug free.

True, even better if the implementation is correct-by-construction.  In reality though, even machine checked proofs [do not provide](https://nadim.micro.blog/2019/04/11/selfies-reflections-on.html) absolute confidence. Anyway, engineers are usually happy with less. SPIN for example supports *[model-driven verification](https://link.springer.com/chapter/10.1007/978-3-540-24732-6_6)* which apparently is good enough for NASA.

> TLC can be slow, really slow
>
>    I ran TLC on my BPaxos stuff on 64 cores for hours and I exhausted 16 GB of disk before it could finish. Could take days to simulate.

In comparison, how long did it take you to find the inductive invariant and write a machine checked proof (compare ["Proof assistants are addictive and a huge time sink."](https://xavierleroy.org/talks/IHP-2014.pdf))?

By the way, can you share your BPaxos spec to study it as part of our [scalability tests](https://github.com/tlaplus/tlaplus/tree/master/general/performance)?

Also, [apalache](https://github.com/konnov/apalache) might in the future scale to larger models.

> Sometimes hard to check if your system is doing what you expect.

I'm inclined to argue that this problem is not unique for TLA+. ;-)

**Comment by mwhittaker** [comment]
Hi @lemmy! Thanks so much for taking a look at this repo and taking the time to write out all these clarifications. I'm only an amateur TLA+ user, so getting feedback from an expert like yourself is super useful and very much appreciated. I've updated the README to point to this issue, so others know to read through it as well. 

Here are [my BPaxos specs](https://github.com/mwhittaker/bipartisan_paxos/tree/67d132189cc80b0d302051d7f1dd161261c5c0af/tla). [BPaxos](https://mwhittaker.github.io/publications/bipartisan_paxos.pdf) is actually a family of five protocols: Simple BPaxos, Unsafe BPaxos, Unanimous BPaxos, Deadlock BPaxos, and Majority Commit BPaxos. Note that I only have complete specs for some of them.
